name: raksa_vault
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0

  # Local Authentication & Storage
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4

  # Local Database (Drift) & Storage Paths
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.0
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation for Drift Database
  drift_dev: ^2.28.0
  build_runner: ^2.5.0

  # Firebase CLI Helper Tool
  flutterfire_cli: ^1.4.0

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/image_2026-06-30_14-08-59.png
